Add msg
Signed-off-by: Jon Kartago Lamida <me@lamida.net>

diff --git a/.github/workflows/pr-checker.yml b/.github/workflows/pr-checker.yml
--- a/.github/workflows/pr-checker.yml
+++ b/.github/workflows/pr-checker.yml
@@ -29,4 +29,8 @@ jobs:
     name: PR Checker
     if: always()
     steps:
-        - run: if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }} ; then exit 1; fi
+        - run: |
+            if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }} ; then 
+                echo "Some of required jobs are skipped or failed";
+                exit 1; 
+            fi
