Fail one of the job
Signed-off-by: Jon Kartago Lamida <me@lamida.net>

diff --git a/.github/workflows/pr-checker.yml b/.github/workflows/pr-checker.yml
--- a/.github/workflows/pr-checker.yml
+++ b/.github/workflows/pr-checker.yml
@@ -18,6 +18,7 @@ jobs:
     runs-on: ubuntu-latest
     steps: 
         - run: echo "fine 32"
+        - run: exit 1; # This will fail the job
 
   pr-checker:
     runs-on: ubuntu-latest
@@ -28,7 +29,9 @@ jobs:
     name: PR Checker
     if: always()
     steps:
-        - run: |
+        - name: Check CI jobs result
+          run: |
+            # Checking whether all dependent jobs are successful
             if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }} ; then 
                 echo "Some of the required jobs are skipped or failed";
                 exit 1; 
